server:
  port: 8080
  servlet:
    context-path: /ssps

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/ssps_server"
    username: root
    password: Tatcalavie51
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey : "qGyWNJwIHP6vMaJ8gOxJNgHxpdyZWBFfg9haB06KrtGB/MHu5TwTeZ8q2HZ9CVRW"
