server:
  port: 8080
  servlet:
    context-path: /ssps

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/ssps_server"
    username: kienle
    password: kienle@2105
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true